"""removing parcel id from myorder

Revision ID: dafe716744e0
Revises: 97790ea92529
Create Date: 2024-08-25 21:56:13.209353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafe716744e0'
down_revision = '97790ea92529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.drop_constraint('myorders_parcel_id_fkey', type_='foreignkey')
        batch_op.drop_column('parcel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('myorders_parcel_id_fkey', 'parcels', ['parcel_id'], ['id'])

    # ### end Alembic commands ###
