"""adding cost column

Revision ID: 629818605580
Revises: 6d929d30d41f
Create Date: 2024-08-13 11:59:51.592658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629818605580'
down_revision = '6d929d30d41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
