"""empty message

Revision ID: 69a650c631db
Revises: 8090332a90b8
Create Date: 2024-08-11 01:26:26.673183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a650c631db'
down_revision = '8090332a90b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipientname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipientcontact', sa.String(length=50), nullable=False))

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient_contact', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('recipient_contact')
        batch_op.drop_column('recipient_name')

    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.drop_column('recipientcontact')
        batch_op.drop_column('recipientname')

    # ### end Alembic commands ###
