"""empty message

Revision ID: 6d929d30d41f
Revises: f7880bc41b04
Create Date: 2024-08-11 21:14:46.769798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d929d30d41f'
down_revision = 'f7880bc41b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_value'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_value'"))

    # ### end Alembic commands ###
