"""Add recipient_name and recipient_contact to MyOrder

Revision ID: 6faa469f16d5
Revises: 69a650c631db
Create Date: 2024-08-11 21:12:58.721589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faa469f16d5'
down_revision = '69a650c631db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('recipient_contact', sa.String(length=50), nullable=False))
        batch_op.drop_column('recipientcontact')
        batch_op.drop_column('recipientname')

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('recipient_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_contact', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient_name', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipientname', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipientcontact', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('recipient_contact')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
