"""updated model relationships

Revision ID: 7479f224d236
Revises: 7cd4951202ca
Create Date: 2024-07-30 20:30:06.063374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7479f224d236'
down_revision = '7cd4951202ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=120), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_constraint_name', type_='foreignkey')
        batch_op.drop_column('parcel_id')

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_constraint_name', type_='foreignkey')
        batch_op.drop_constraint('fk_constraint_name', type_='foreignkey')
        batch_op.drop_column('destination_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('destination_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'destinations', ['destination_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'parcels', ['parcel_id'], ['id'])

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
