"""adding recipient details

Revision ID: f7880bc41b04
Revises: 8090332a90b8
Create Date: 2024-08-11 14:24:51.016874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7880bc41b04'
down_revision = '8090332a90b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=50), nullable=False, server_default='default_value'))
        batch_op.add_column(sa.Column('recipient_contact', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    op.execute("UPDATE myorders SET recipient_contact = 0 WHERE recipient_contact IS NULL")

    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.alter_column('recipient_contact', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.drop_column('recipient_contact')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
